apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az-managed-premium-pvc
spec:
  storageClassName: managed-premium
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-vol-disk-dynamic-deploy
  labels:
    app: data-vol-disk-dynamic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-vol-disk-dynamic
  template:
    metadata:
      name: data-vol-disk-dynamic-pod
      labels:
        app: data-vol-disk-dynamic
    spec:
      containers:
      - name: data-vol-disk-dynamic
        image: kvkakssecurityacr.azurecr.io/aks-data-volumes-demo
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: files
            mountPath: /files
      volumes:
      - name: files
        persistentVolumeClaim:
          claimName: az-managed-premium-pvc
      restartPolicy: Always 

---

apiVersion: v1
kind: Service
metadata:
  name: data-vol-disk-dynamic-svc
spec:
  selector:
    app: data-vol-disk-dynamic
  ports:
    - port: 80
  type: LoadBalancer
  
  