apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-vol-disk-static-deploy
  labels:
    app: data-vol-disk-static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-vol-disk-static
  template:
    metadata:
      name: data-vol-disk-pod
      labels:
        app: data-vol-disk-static
    spec:
      containers:
      - name: data-vol-disk-static
        image: kvkakssecurityacr.azurecr.io/aks-data-volumes-demo
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: files
            mountPath: /files
      volumes:
      - name: files
        azureDisk:
          kind: Managed
          diskName: kvkakssecuritydisk01
          diskURI: <your-disk-uri-here>
      restartPolicy: Always 

---

apiVersion: v1
kind: Service
metadata:
  name: data-vol-disk-static-svc
spec:
  selector:
    app: data-vol-disk-static
  ports:
    - port: 80
  type: LoadBalancer
  
  